### ISSUE TITLE
Box name cannot be "null"

### ISSUE THREAD

**Issue by dixonsiu** [personium/docs#86]
[Create Box](https://personium.github.io/ja/apiref/1.5.7/256_Create_Box.html) states that Box name can be the followings.  

    Number of digits: 1 - 128
    Character type: Single-byte alphanumeric characters, hyphens ("-"), and underscores ("_")
    However, the string cannot start with a single-byte hyphen ("-") or underscore ("_")
    null

The correct specification for Box name should be:

    Number of digits: 1 - 128
    Character type: Single-byte alphanumeric characters, hyphens ("-"), and underscores ("_")
    However, the string cannot start with a single-byte hyphen ("-") or underscore ("_")

**Comment by shimono** [comment]
This seems to be already resolved
