### ISSUE TITLE
Correct cURL sample of unit user's document

### ISSUE THREAD

**Issue by KourokiTakuto** [personium/docs#87]
Correspond to the following two points

1. The method of specifying the owner name in creation and acquisition of cell is "{UnitURL}/{UnitUserName}".
It corresponds to change to "personium-localunit:/{CellName}/#{UnitUserName}".

1. The method of cURL sample issuing unit user token is GET.
The correct answer is corrected for POST.

**Comment by hiroaki-shibata** [comment]
This issue include two issues, 1 & 2. Number 2 (bug) can correct soon , but Number 1 (enhancement) can not correct soon. So , I change only number 2 , and create new Issue for number 1.
